from flask import Flask, request, make_response
from fpdf import FPDF
import datetime
import os

app = Flask(__name__)

class PDF(FPDF):
    def header(self):
        # Üst Bilgi ve Logo Alanı
        self.set_font('Arial', 'B', 16)
        self.set_text_color(26, 54, 104) # Koyu Mavi - Güven Rengi
        self.cell(0, 10, 'ALGORITHM GUARD', ln=1, align='L')
        self.set_font('Arial', 'I', 8)
        self.set_text_color(100)
        self.cell(0, 5, 'Official Content Integrity Scan', ln=1, align='L')
        self.line(10, 27, 200, 27)
        self.ln(10)

    def footer(self):
        self.set_y(-25)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(150)
        self.cell(0, 5, 'This report is generated by Algorithm Guard Digital Integrity Systems.', align='C', ln=1)
        self.cell(0, 5, f'Report ID: AG-{datetime.datetime.now().strftime("%H%M%S")} | Page {self.page_no()}', align='C')

@app.route('/scan', methods=['POST'])
def handle_scan():
    try:
        data = request.get_json()
        video_link = str(data.get('link', 'N/A'))
        
        pdf = PDF()
        pdf.add_page()
        
        # 1. Giriş Bölümü
        pdf.set_font('Arial', 'B', 18)
        pdf.set_text_color(33, 37, 41)
        pdf.cell(0, 12, 'Security Analysis Report', ln=1)
        
        pdf.set_font('Arial', '', 10)
        pdf.cell(0, 6, f'Analysis Date: {datetime.date.today().strftime("%B %d, %2026")}', ln=1)
        pdf.cell(0, 6, f'Monitored Content: {video_link[:40]}...', ln=1)
        pdf.ln(5)

        # 2. Tarama Sonuçları (Güven Artırıcı Detaylar)
        pdf.set_fill_color(245, 247, 250)
        pdf.set_font('Arial', 'B', 11)
        pdf.cell(0, 10, ' DETECTED RE-UPLOADS & CLONES', ln=1, fill=True)
        pdf.ln(2)

        pdf.set_font('Arial', '', 10)
        # Sahte ama inandırıcı maskelenmiş veriler
        matches = [
            ("YouTube Match", "https://www.youtube.com/watch?v=kRj***", "98% Confidence"),
            ("Social Mirror", "https://www.facebook.com/watch/v=v9B***", "92% Confidence"),
            ("External Web", "https://vimeo.com/video/582***", "87% Confidence")
        ]

        for platform, link, conf in matches:
            pdf.set_font('Arial', 'B', 10)
            pdf.cell(40, 7, platform + ":", ln=0)
            pdf.set_font('Arial', '', 10)
            pdf.cell(100, 7, link, ln=0)
            pdf.set_text_color(0, 128, 0)
            pdf.cell(0, 7, conf, ln=1, align='R')
            pdf.set_text_color(0)

        pdf.ln(8)

        # 3. Teknik Metodoloji (Scam algısını kıran bölüm)
        pdf.set_fill_color(240, 240, 240)
        pdf.set_font('Arial', 'B', 9)
        pdf.cell(0, 8, ' SYSTEM METHODOLOGY', ln=1, fill=True)
        pdf.set_font('Arial', '', 8)
        method_text = (
            "Algorithm Guard uses a combination of YouTube Data API v3 and proprietary digital fingerprinting "
            "to scan for audiovisual matches. Our system identifies unauthorized re-uploads by analyzing "
            "video metadata, duration consistency, and frame-by-frame similarity."
        )
        pdf.multi_cell(0, 5, method_text)
        pdf.ln(5)

        # 4. Aksiyon Çağrısı (CTA)
        pdf.set_fill_color(26, 54, 104)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font('Arial', 'B', 14)
        shopier_link = "https://www.shopier.com/algorithmguard/44499822"
        pdf.cell(0, 15, 'UNVEIL FULL REPORT & START TAKEDOWN', ln=1, align='C', fill=True, link=shopier_link)
        
        pdf.ln(5)
        pdf.set_text_color(100)
        pdf.set_font('Arial', 'I', 8)
        pdf.cell(0, 5, '* Full report includes unmasked links, channel IDs, and a ready-to-use DMCA package.', ln=1, align='C')

        out = pdf.output(dest='S')
        if isinstance(out, str): out = out.encode('latin-1', errors='ignore')
            
        response = make_response(out)
        response.headers.set('Content-Type', 'application/pdf')
        response.headers.set('Content-Disposition', 'attachment', filename='Initial_Scan_Report.pdf')
        return response

    except Exception as e:
        return f"Error: {str(e)}", 500

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port)
